window.LOCAL_FOOD_CATALOG = [
  { name: "Arroz branco cozido", quantity: "100g", calories: 130, protein: 2.7, carbs: 28.2, fat: 0.3, tags: ["arroz", "branco", "cozido"] },
  { name: "Arroz integral cozido", quantity: "100g", calories: 112, protein: 2.6, carbs: 23.5, fat: 1, tags: ["arroz", "integral", "cozido"] },
  { name: "Arroz parboilizado cozido", quantity: "100g", calories: 123, protein: 2.9, carbs: 26, fat: 0.4, tags: ["arroz", "parboilizado"] },
  { name: "Arroz carreteiro", quantity: "100g", calories: 178, protein: 8.5, carbs: 21, fat: 6, tags: ["arroz", "carreteiro"] },
  { name: "Feijao carioca cozido", quantity: "100g", calories: 76, protein: 4.8, carbs: 13.6, fat: 0.5, tags: ["feijao", "carioca"] },
  { name: "Feijao preto cozido", quantity: "100g", calories: 77, protein: 4.5, carbs: 14, fat: 0.5, tags: ["feijao", "preto"] },
  { name: "Feijao branco cozido", quantity: "100g", calories: 91, protein: 6, carbs: 16, fat: 0.6, tags: ["feijao", "branco"] },
  { name: "Feijao tropeiro", quantity: "100g", calories: 210, protein: 9, carbs: 18, fat: 11, tags: ["feijao", "tropeiro", "mineiro"] },
  { name: "Lentilha cozida", quantity: "100g", calories: 93, protein: 6.3, carbs: 16.3, fat: 0.4, tags: ["lentilha"] },
  { name: "Grao-de-bico cozido", quantity: "100g", calories: 164, protein: 8.9, carbs: 27.4, fat: 2.6, tags: ["grao", "grao-de-bico", "bico"] },
  { name: "Macarrao cozido", quantity: "100g", calories: 157, protein: 5.8, carbs: 30.9, fat: 0.9, tags: ["macarrao", "massa"] },
  { name: "Macarrao alho e oleo", quantity: "100g", calories: 220, protein: 5.5, carbs: 31, fat: 8.5, tags: ["macarrao", "alho", "oleo"] },
  { name: "Lasanha a bolonhesa", quantity: "100g", calories: 163, protein: 10, carbs: 14, fat: 7.8, tags: ["lasanha", "bolonhesa"] },
  { name: "Nhoque ao sugo", quantity: "100g", calories: 134, protein: 3.2, carbs: 28, fat: 1.2, tags: ["nhoque"] },
  { name: "Pure de batata", quantity: "100g", calories: 113, protein: 2.1, carbs: 17.7, fat: 4.1, tags: ["pure", "batata"] },
  { name: "Batata inglesa cozida", quantity: "100g", calories: 77, protein: 2, carbs: 17, fat: 0.1, tags: ["batata", "inglesa"] },
  { name: "Batata doce cozida", quantity: "100g", calories: 86, protein: 1.6, carbs: 20.1, fat: 0.1, tags: ["batata", "doce"] },
  { name: "Batata frita", quantity: "100g", calories: 312, protein: 3.4, carbs: 41.4, fat: 15, tags: ["batata", "frita"] },
  { name: "Mandioca cozida", quantity: "100g", calories: 160, protein: 1.4, carbs: 38.1, fat: 0.3, tags: ["mandioca", "aipim", "macaxeira"] },
  { name: "Polenta frita", quantity: "100g", calories: 240, protein: 3.5, carbs: 29, fat: 12, tags: ["polenta", "frita"] },
  { name: "Farofa", quantity: "30g", calories: 120, protein: 1.6, carbs: 18, fat: 4.8, tags: ["farofa"] },
  { name: "Cuscuz nordestino", quantity: "100g", calories: 112, protein: 2.4, carbs: 25.3, fat: 0.7, tags: ["cuscuz", "nordestino"] },
  { name: "Tapioca", quantity: "100g", calories: 358, protein: 0.2, carbs: 88.7, fat: 0, tags: ["tapioca", "beiju"] },
  { name: "Pao frances", quantity: "1 unidade", calories: 135, protein: 4.5, carbs: 26, fat: 1.7, tags: ["pao", "frances"] },
  { name: "Pao integral", quantity: "1 fatia", calories: 70, protein: 3, carbs: 12, fat: 1.1, tags: ["pao", "integral"] },
  { name: "Pao de forma branco", quantity: "2 fatias", calories: 134, protein: 4.2, carbs: 24, fat: 2.1, tags: ["pao", "forma"] },
  { name: "Pao de queijo", quantity: "1 unidade", calories: 90, protein: 2.1, carbs: 9.8, fat: 5.1, tags: ["pao", "queijo"] },
  { name: "Croissant de queijo", quantity: "1 unidade", calories: 300, protein: 7, carbs: 27, fat: 18, tags: ["croissant", "queijo"] },
  { name: "Torrada", quantity: "4 unidades", calories: 120, protein: 3.6, carbs: 22, fat: 2.1, tags: ["torrada"] },
  { name: "Bolo de cenoura", quantity: "1 fatia", calories: 245, protein: 3.2, carbs: 36, fat: 10, tags: ["bolo", "cenoura"] },
  { name: "Bolo de chocolate", quantity: "100g", calories: 371, protein: 5.3, carbs: 53, fat: 15, tags: ["bolo", "chocolate"] },
  { name: "Aveia em flocos", quantity: "100g", calories: 389, protein: 16.9, carbs: 66.3, fat: 6.9, tags: ["aveia"] },
  { name: "Granola", quantity: "30g", calories: 134, protein: 3.3, carbs: 20, fat: 4.7, tags: ["granola"] },
  { name: "Leite integral", quantity: "200ml", calories: 122, protein: 6.2, carbs: 9.4, fat: 6.6, tags: ["leite", "integral"] },
  { name: "Leite desnatado", quantity: "200ml", calories: 70, protein: 6.8, carbs: 10, fat: 0.2, tags: ["leite", "desnatado"] },
  { name: "Iogurte natural", quantity: "170g", calories: 100, protein: 5.8, carbs: 8.2, fat: 4.2, tags: ["iogurte", "natural"] },
  { name: "Iogurte grego", quantity: "170g", calories: 130, protein: 9.4, carbs: 15, fat: 4.5, tags: ["iogurte", "grego"] },
  { name: "Queijo minas", quantity: "100g", calories: 260, protein: 17.4, carbs: 1.6, fat: 20.4, tags: ["queijo", "minas", "branco"] },
  { name: "Mussarela", quantity: "100g", calories: 280, protein: 22, carbs: 3, fat: 20, tags: ["mussarela", "queijo"] },
  { name: "Presunto", quantity: "30g", calories: 49, protein: 7.3, carbs: 1, fat: 1.8, tags: ["presunto", "frio"] },
  { name: "Mortadela", quantity: "30g", calories: 97, protein: 3.6, carbs: 1.6, fat: 8.6, tags: ["mortadela", "frio"] },
  { name: "Peito de peru", quantity: "100g", calories: 135, protein: 18, carbs: 3.7, fat: 2, tags: ["peito de peru", "frio"] },
  { name: "Salame", quantity: "30g", calories: 122, protein: 6.8, carbs: 0.5, fat: 10.4, tags: ["salame", "frio"] },
  { name: "Lombo canadense", quantity: "30g", calories: 43, protein: 6.4, carbs: 0.7, fat: 1.5, tags: ["lombo", "canadense", "frio"] },
  { name: "Provolone", quantity: "30g", calories: 106, protein: 7.5, carbs: 0.6, fat: 8.1, tags: ["provolone", "queijo"] },
  { name: "Parmesao", quantity: "30g", calories: 118, protein: 10.7, carbs: 1, fat: 7.8, tags: ["parmesao", "queijo"] },
  { name: "Queijo prato", quantity: "100g", calories: 330, protein: 21, carbs: 2.3, fat: 27, tags: ["queijo", "prato"] },
  { name: "Ricota", quantity: "50g", calories: 70, protein: 5.6, carbs: 1.5, fat: 4.7, tags: ["ricota", "queijo"] },
  { name: "Requeijao", quantity: "30g", calories: 76, protein: 2.2, carbs: 1.3, fat: 7, tags: ["requeijao"] },
  { name: "Cream cheese", quantity: "30g", calories: 103, protein: 1.8, carbs: 1.7, fat: 10, tags: ["cream", "cheese"] },
  { name: "Manteiga", quantity: "1 colher", calories: 102, protein: 0.1, carbs: 0, fat: 11.5, tags: ["manteiga"] },
  { name: "Maionese", quantity: "15g", calories: 102, protein: 0.2, carbs: 0.6, fat: 11, tags: ["maionese", "molho"] },
  { name: "Ketchup", quantity: "15g", calories: 17, protein: 0.2, carbs: 4.2, fat: 0, tags: ["ketchup", "molho"] },
  { name: "Mostarda", quantity: "15g", calories: 10, protein: 0.6, carbs: 0.8, fat: 0.6, tags: ["mostarda", "molho"] },
  { name: "Catupiry", quantity: "30g", calories: 78, protein: 1.8, carbs: 1.7, fat: 7.2, tags: ["catupiry", "queijo"] },
  { name: "Peito de frango grelhado", quantity: "100g", calories: 165, protein: 31, carbs: 0, fat: 3.6, tags: ["frango", "peito", "grelhado"] },
  { name: "Frango desfiado", quantity: "100g", calories: 151, protein: 28, carbs: 0, fat: 3.8, tags: ["frango", "desfiado"] },
  { name: "Frango assado", quantity: "100g", calories: 190, protein: 28, carbs: 0, fat: 8.2, tags: ["frango", "assado"] },
  { name: "Strogonoff de frango", quantity: "100g", calories: 180, protein: 14, carbs: 5, fat: 11, tags: ["strogonoff", "frango"] },
  { name: "Carne bovina magra", quantity: "100g", calories: 250, protein: 26, carbs: 0, fat: 15, tags: ["carne", "bovina", "magra"] },
  { name: "Patinho moido", quantity: "100g", calories: 270, protein: 25, carbs: 0, fat: 18, tags: ["patinho", "carne", "moido"] },
  { name: "Carne moida refogada", quantity: "100g", calories: 270, protein: 25, carbs: 2, fat: 18, tags: ["carne", "moida", "refogada"] },
  { name: "Contra-file grelhado", quantity: "100g", calories: 239, protein: 25, carbs: 0, fat: 15, tags: ["contra-file", "carne"] },
  { name: "Picanha grelhada", quantity: "100g", calories: 289, protein: 26, carbs: 0, fat: 20, tags: ["picanha", "carne"] },
  { name: "Alcatra grelhada", quantity: "100g", calories: 220, protein: 29, carbs: 0, fat: 11, tags: ["alcatra", "carne"] },
  { name: "Lombo suino assado", quantity: "100g", calories: 242, protein: 27, carbs: 0, fat: 14, tags: ["lombo", "suino", "porco"] },
  { name: "Costela assada", quantity: "100g", calories: 376, protein: 22, carbs: 0, fat: 32, tags: ["costela", "carne"] },
  { name: "Tilapia grelhada", quantity: "100g", calories: 129, protein: 26, carbs: 0, fat: 2.7, tags: ["tilapia", "peixe"] },
  { name: "Salmão grelhado", quantity: "100g", calories: 208, protein: 20.4, carbs: 0, fat: 13.4, tags: ["salmao", "salmão", "peixe"] },
  { name: "Sardinha grelhada", quantity: "100g", calories: 208, protein: 24.6, carbs: 0, fat: 11.5, tags: ["sardinha", "peixe"] },
  { name: "Atum enlatado", quantity: "100g", calories: 130, protein: 28, carbs: 0, fat: 1, tags: ["atum", "enlatado", "agua"] },
  { name: "Ovo de galinha", quantity: "1 unidade", calories: 70, protein: 6.3, carbs: 0.4, fat: 4.8, tags: ["ovo", "ovo inteiro"] },
  { name: "Clara de ovo", quantity: "1 unidade", calories: 17, protein: 3.6, carbs: 0.2, fat: 0, tags: ["clara", "ovo"] },
  { name: "Omelete simples", quantity: "2 ovos", calories: 154, protein: 12.5, carbs: 1, fat: 10.8, tags: ["omelete", "ovo"] },
  { name: "Banana prata", quantity: "1 unidade", calories: 89, protein: 1.1, carbs: 22.8, fat: 0.3, tags: ["banana", "fruta"] },
  { name: "Banana nanica", quantity: "1 unidade", calories: 89, protein: 1.1, carbs: 22.8, fat: 0.3, tags: ["banana", "nanica"] },
  { name: "Maca", quantity: "1 unidade", calories: 52, protein: 0.3, carbs: 13.8, fat: 0.2, tags: ["maca", "maçã", "fruta"] },
  { name: "Laranja", quantity: "1 unidade", calories: 47, protein: 0.9, carbs: 11.8, fat: 0.1, tags: ["laranja", "fruta"] },
  { name: "Pera", quantity: "1 unidade", calories: 85, protein: 0.6, carbs: 22.5, fat: 0.2, tags: ["pera", "fruta"] },
  { name: "Mamao papaia", quantity: "100g", calories: 43, protein: 0.5, carbs: 10.8, fat: 0.1, tags: ["mamao", "mamão", "papaia"] },
  { name: "Manga", quantity: "100g", calories: 60, protein: 0.8, carbs: 15, fat: 0.4, tags: ["manga"] },
  { name: "Melancia", quantity: "100g", calories: 30, protein: 0.6, carbs: 7.6, fat: 0.2, tags: ["melancia"] },
  { name: "Melão", quantity: "100g", calories: 29, protein: 0.7, carbs: 7.5, fat: 0, tags: ["melao", "melon"] },
  { name: "Abacaxi", quantity: "100g", calories: 50, protein: 0.5, carbs: 13.1, fat: 0.1, tags: ["abacaxi"] },
  { name: "Uva", quantity: "100g", calories: 69, protein: 0.7, carbs: 18.1, fat: 0.2, tags: ["uva", "fruta"] },
  { name: "Morango", quantity: "100g", calories: 32, protein: 0.7, carbs: 7.7, fat: 0.3, tags: ["morango", "fruta"] },
  { name: "Acai na tigela", quantity: "200g", calories: 220, protein: 3, carbs: 32, fat: 9, tags: ["acai", "tigela"] },
  { name: "Abacate", quantity: "100g", calories: 160, protein: 2, carbs: 8.5, fat: 14.7, tags: ["abacate"] },
  { name: "Pasta de amendoim", quantity: "15g", calories: 90, protein: 3.8, carbs: 3.2, fat: 7.2, tags: ["pasta", "amendoim"] },
  { name: "Amendoim torrado", quantity: "100g", calories: 567, protein: 25.8, carbs: 16.1, fat: 49.2, tags: ["amendoim"] },
  { name: "Castanha de caju", quantity: "100g", calories: 553, protein: 18.2, carbs: 30.2, fat: 43.8, tags: ["castanha", "caju"] },
  { name: "Nozes", quantity: "100g", calories: 654, protein: 15.2, carbs: 13.7, fat: 65.2, tags: ["nozes"] },
  { name: "Whey protein", quantity: "30g", calories: 120, protein: 24, carbs: 3, fat: 2, tags: ["whey", "protein"] },
  { name: "Barra de proteina", quantity: "1 unidade", calories: 210, protein: 15, carbs: 20, fat: 8, tags: ["barra", "proteina"] },
  { name: "Coxinha", quantity: "1 unidade", calories: 250, protein: 10, carbs: 20, fat: 14, tags: ["coxinha", "salgado"] },
  { name: "Esfiha de carne", quantity: "1 unidade", calories: 190, protein: 8, carbs: 22, fat: 8, tags: ["esfiha", "carne"] },
  { name: "Esfiha de queijo", quantity: "1 unidade", calories: 205, protein: 7, carbs: 21, fat: 10, tags: ["esfiha", "queijo"] },
  { name: "Esfiha de frango", quantity: "1 unidade", calories: 198, protein: 9, carbs: 21, fat: 8, tags: ["esfiha", "frango"] },
  { name: "Esfiha de calabresa", quantity: "1 unidade", calories: 214, protein: 8, carbs: 20, fat: 11, tags: ["esfiha", "calabresa"] },
  { name: "Empada de frango", quantity: "1 unidade", calories: 230, protein: 6, carbs: 18, fat: 15, tags: ["empada", "frango"] },
  { name: "Pastel de queijo", quantity: "1 unidade", calories: 285, protein: 8, carbs: 24, fat: 17, tags: ["pastel", "queijo"] },
  { name: "Pastel de carne", quantity: "1 unidade", calories: 300, protein: 11, carbs: 23, fat: 18, tags: ["pastel", "carne"] },
  { name: "Pastel de frango com catupiry", quantity: "1 unidade", calories: 315, protein: 12, carbs: 24, fat: 19, tags: ["pastel", "frango", "catupiry"] },
  { name: "Pastel de pizza", quantity: "1 unidade", calories: 305, protein: 10, carbs: 25, fat: 18, tags: ["pastel", "pizza"] },
  { name: "Pastel de palmito", quantity: "1 unidade", calories: 278, protein: 6, carbs: 25, fat: 17, tags: ["pastel", "palmito"] },
  { name: "Pastel de camarao", quantity: "1 unidade", calories: 298, protein: 10, carbs: 23, fat: 18, tags: ["pastel", "camarao"] },
  { name: "Pastel de chocolate", quantity: "1 unidade", calories: 320, protein: 5, carbs: 33, fat: 19, tags: ["pastel", "chocolate", "doce"] },
  { name: "Pao na chapa", quantity: "1 unidade", calories: 185, protein: 4.5, carbs: 26, fat: 7, tags: ["pao", "chapa"] },
  { name: "Hot dog simples", quantity: "1 unidade", calories: 310, protein: 11, carbs: 29, fat: 17, tags: ["hot dog", "cachorro-quente"] },
  { name: "Hot dog duplo", quantity: "1 unidade", calories: 430, protein: 17, carbs: 35, fat: 25, tags: ["hot dog", "duplo", "cachorro-quente"] },
  { name: "X-Burger", quantity: "1 unidade", calories: 450, protein: 24, carbs: 31, fat: 25, tags: ["x-burger", "hamburguer"] },
  { name: "X-Salada", quantity: "1 unidade", calories: 490, protein: 26, carbs: 34, fat: 28, tags: ["x-salada", "hamburguer"] },
  { name: "X-Bacon", quantity: "1 unidade", calories: 585, protein: 29, carbs: 35, fat: 35, tags: ["x-bacon", "hamburguer"] },
  { name: "X-Tudo", quantity: "1 unidade", calories: 790, protein: 38, carbs: 48, fat: 49, tags: ["x-tudo", "hamburguer"] },
  { name: "X-Frango", quantity: "1 unidade", calories: 470, protein: 27, carbs: 32, fat: 24, tags: ["x-frango", "hamburguer", "frango"] },
  { name: "X-Egg", quantity: "1 unidade", calories: 520, protein: 28, carbs: 33, fat: 30, tags: ["x-egg", "hamburguer", "ovo"] },
  { name: "Big Mac", quantity: "1 unidade", calories: 503, protein: 26, carbs: 43, fat: 26, tags: ["big mac", "mcdonalds"] },
  { name: "Cheeseburger McDonalds", quantity: "1 unidade", calories: 300, protein: 15, carbs: 33, fat: 12, tags: ["cheeseburger", "mcdonalds"] },
  { name: "Quarterao com queijo", quantity: "1 unidade", calories: 523, protein: 30, carbs: 42, fat: 27, tags: ["quarterao", "mcdonalds"] },
  { name: "McChicken", quantity: "1 unidade", calories: 398, protein: 17, carbs: 41, fat: 18, tags: ["mcchicken", "mcdonalds"] },
  { name: "McNuggets 6 unidades", quantity: "6 unidades", calories: 261, protein: 15, carbs: 16, fat: 15, tags: ["mcnuggets", "mcdonalds"] },
  { name: "Whopper", quantity: "1 unidade", calories: 657, protein: 28, carbs: 49, fat: 39, tags: ["whopper", "burger king"] },
  { name: "Cheeseburger Burger King", quantity: "1 unidade", calories: 302, protein: 15, carbs: 31, fat: 13, tags: ["cheeseburger", "burger king"] },
  { name: "Chicken Duplo Burger King", quantity: "1 unidade", calories: 544, protein: 28, carbs: 38, fat: 31, tags: ["chicken", "burger king"] },
  { name: "Cheeseburger", quantity: "1 unidade", calories: 300, protein: 15, carbs: 31, fat: 13, tags: ["cheeseburger", "hamburguer"] },
  { name: "Pizza mussarela", quantity: "1 fatia", calories: 280, protein: 12, carbs: 30, fat: 12, tags: ["pizza", "mussarela"] },
  { name: "Pizza calabresa", quantity: "1 fatia", calories: 296, protein: 13, carbs: 29, fat: 14, tags: ["pizza", "calabresa"] },
  { name: "Pizza portuguesa", quantity: "1 fatia", calories: 280, protein: 12, carbs: 27, fat: 13, tags: ["pizza", "portuguesa"] },
  { name: "Pizza frango com catupiry", quantity: "1 fatia", calories: 310, protein: 14, carbs: 28, fat: 16, tags: ["pizza", "frango", "catupiry"] },
  { name: "Pizza marguerita", quantity: "1 fatia", calories: 265, protein: 11, carbs: 28, fat: 12, tags: ["pizza", "marguerita"] },
  { name: "Pizza quatro queijos", quantity: "1 fatia", calories: 325, protein: 14, carbs: 27, fat: 18, tags: ["pizza", "quatro queijos"] },
  { name: "Pizza bacon", quantity: "1 fatia", calories: 318, protein: 13, carbs: 27, fat: 17, tags: ["pizza", "bacon"] },
  { name: "Pizza pepperoni", quantity: "1 fatia", calories: 310, protein: 13, carbs: 28, fat: 16, tags: ["pizza", "pepperoni"] },
  { name: "Pizza chocolate", quantity: "1 fatia", calories: 340, protein: 5, carbs: 46, fat: 15, tags: ["pizza", "chocolate", "doce"] },
  { name: "Nuggets", quantity: "100g", calories: 296, protein: 15, carbs: 20, fat: 18, tags: ["nuggets"] },
  { name: "Fogazza de queijo", quantity: "1 unidade", calories: 340, protein: 11, carbs: 31, fat: 19, tags: ["fogazza", "queijo"] },
  { name: "Fogazza de carne", quantity: "1 unidade", calories: 365, protein: 14, carbs: 30, fat: 21, tags: ["fogazza", "carne"] },
  { name: "Fogazza de frango com catupiry", quantity: "1 unidade", calories: 378, protein: 15, carbs: 31, fat: 22, tags: ["fogazza", "frango", "catupiry"] },
  { name: "Fogazza de calabresa", quantity: "1 unidade", calories: 388, protein: 14, carbs: 30, fat: 24, tags: ["fogazza", "calabresa"] },
  { name: "Fogazza de pizza", quantity: "1 unidade", calories: 360, protein: 12, carbs: 32, fat: 20, tags: ["fogazza", "pizza"] },
  { name: "Fogazza de presunto e queijo", quantity: "1 unidade", calories: 372, protein: 14, carbs: 31, fat: 21, tags: ["fogazza", "presunto", "queijo"] },
  { name: "Fogazza de palmito", quantity: "1 unidade", calories: 332, protein: 8, carbs: 33, fat: 18, tags: ["fogazza", "palmito"] },
  { name: "Fogazza doce de chocolate", quantity: "1 unidade", calories: 395, protein: 6, carbs: 44, fat: 22, tags: ["fogazza", "chocolate", "doce"] },
  { name: "Feijoada", quantity: "1 concha", calories: 240, protein: 14, carbs: 16, fat: 13, tags: ["feijoada"] },
  { name: "Moqueca de peixe", quantity: "100g", calories: 145, protein: 15, carbs: 4, fat: 8, tags: ["moqueca", "peixe"] },
  { name: "Bobo de camarao", quantity: "100g", calories: 176, protein: 9, carbs: 8, fat: 12, tags: ["bobo", "camarao"] },
  { name: "Vatapa", quantity: "100g", calories: 255, protein: 6, carbs: 10, fat: 21, tags: ["vatapa"] },
  { name: "Acaraje", quantity: "1 unidade", calories: 289, protein: 11, carbs: 23, fat: 17, tags: ["acaraje"] },
  { name: "Escondidinho de carne", quantity: "100g", calories: 168, protein: 10, carbs: 13, fat: 8, tags: ["escondidinho"] },
  { name: "Escondidinho de frango", quantity: "100g", calories: 158, protein: 11, carbs: 14, fat: 7, tags: ["escondidinho", "frango"] },
  { name: "Frango com quiabo", quantity: "100g", calories: 148, protein: 16, carbs: 5, fat: 7, tags: ["frango", "quiabo"] },
  { name: "Dobradinha", quantity: "100g", calories: 137, protein: 11, carbs: 6, fat: 7, tags: ["dobradinha"] },
  { name: "Virado a paulista", quantity: "100g", calories: 221, protein: 11, carbs: 18, fat: 11, tags: ["virado", "paulista"] },
  { name: "Baião de dois", quantity: "100g", calories: 154, protein: 5.8, carbs: 22, fat: 4.8, tags: ["baiao", "baiao de dois"] },
  { name: "Galinhada", quantity: "100g", calories: 155, protein: 11, carbs: 17, fat: 4.2, tags: ["galinhada"] },
  { name: "Canja de galinha", quantity: "250ml", calories: 120, protein: 9, carbs: 12, fat: 4, tags: ["canja"] },
  { name: "Sopa de legumes", quantity: "250ml", calories: 92, protein: 3.1, carbs: 16, fat: 2, tags: ["sopa", "legumes"] },
  { name: "Salada de alface e tomate", quantity: "100g", calories: 22, protein: 1.2, carbs: 4.3, fat: 0.2, tags: ["salada", "alface", "tomate"] },
  { name: "Tomate", quantity: "100g", calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2, tags: ["tomate"] },
  { name: "Alface", quantity: "100g", calories: 15, protein: 1.4, carbs: 2.9, fat: 0.2, tags: ["alface"] },
  { name: "Cebola", quantity: "50g", calories: 20, protein: 0.6, carbs: 4.6, fat: 0.1, tags: ["cebola"] },
  { name: "Milho verde", quantity: "100g", calories: 98, protein: 3.2, carbs: 17.1, fat: 2.3, tags: ["milho"] },
  { name: "Ervilha", quantity: "100g", calories: 81, protein: 5.4, carbs: 14.5, fat: 0.4, tags: ["ervilha"] },
  { name: "Palmito", quantity: "100g", calories: 28, protein: 2.7, carbs: 4.4, fat: 0.6, tags: ["palmito"] },
  { name: "Azeitona verde", quantity: "30g", calories: 44, protein: 0.3, carbs: 1.1, fat: 4.5, tags: ["azeitona"] },
  { name: "Pepino", quantity: "100g", calories: 15, protein: 0.7, carbs: 3.6, fat: 0.1, tags: ["pepino"] },
  { name: "Cenoura cozida", quantity: "100g", calories: 30, protein: 0.8, carbs: 6.7, fat: 0.2, tags: ["cenoura"] },
  { name: "Brocolis cozido", quantity: "100g", calories: 35, protein: 2.8, carbs: 7.2, fat: 0.4, tags: ["brocolis", "brócolis"] },
  { name: "Couve", quantity: "100g", calories: 49, protein: 3.3, carbs: 8.8, fat: 0.9, tags: ["couve"] },
  { name: "Espinafre", quantity: "100g", calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4, tags: ["espinafre"] },
  { name: "Abobrinha refogada", quantity: "100g", calories: 17, protein: 1.2, carbs: 3.1, fat: 0.3, tags: ["abobrinha"] },
  { name: "Beterraba cozida", quantity: "100g", calories: 32, protein: 1.3, carbs: 7.2, fat: 0.1, tags: ["beterraba"] },
  { name: "Salpicao", quantity: "100g", calories: 180, protein: 8, carbs: 9, fat: 12, tags: ["salpicao"] },
  { name: "Maionese de batata", quantity: "100g", calories: 143, protein: 2.2, carbs: 16, fat: 7.5, tags: ["maionese", "batata"] },
  { name: "Torresmo", quantity: "50g", calories: 290, protein: 30, carbs: 0, fat: 19, tags: ["torresmo"] },
  { name: "Linguica toscana grelhada", quantity: "100g", calories: 301, protein: 14, carbs: 1.2, fat: 27, tags: ["linguica", "toscana"] },
  { name: "Bacon frito", quantity: "30g", calories: 161, protein: 11, carbs: 0.4, fat: 12.4, tags: ["bacon"] },
  { name: "Calabresa acebolada", quantity: "100g", calories: 310, protein: 14, carbs: 2.5, fat: 27, tags: ["calabresa"] },
  { name: "Hamburguer bovino artesanal", quantity: "1 unidade", calories: 250, protein: 17, carbs: 2, fat: 18, tags: ["hamburguer", "artesanal"] },
  { name: "Hamburguer bovino industrial", quantity: "1 unidade", calories: 250, protein: 17, carbs: 4, fat: 18, tags: ["hamburguer"] },
  { name: "File de frango empanado", quantity: "100g", calories: 246, protein: 17, carbs: 14, fat: 13, tags: ["frango", "empanado"] },
  { name: "Anel de cebola", quantity: "100g", calories: 276, protein: 4.3, carbs: 36, fat: 13, tags: ["anel de cebola", "onion rings"] },
  { name: "Batata rustica", quantity: "100g", calories: 192, protein: 2.8, carbs: 28, fat: 7.2, tags: ["batata", "rustica"] },
  { name: "Molho barbecue", quantity: "20g", calories: 34, protein: 0.2, carbs: 8.3, fat: 0.1, tags: ["barbecue", "molho"] },
  { name: "Molho alho", quantity: "20g", calories: 82, protein: 0.5, carbs: 1.2, fat: 8.4, tags: ["alho", "molho"] },
  { name: "Molho rosé", quantity: "20g", calories: 72, protein: 0.3, carbs: 2.1, fat: 7, tags: ["rose", "molho"] },
  { name: "Brigadeiro", quantity: "1 unidade", calories: 90, protein: 1, carbs: 11, fat: 4.5, tags: ["brigadeiro"] },
  { name: "Beijinho", quantity: "1 unidade", calories: 72, protein: 0.9, carbs: 8.1, fat: 4, tags: ["beijinho"] },
  { name: "Pudim de leite", quantity: "1 fatia", calories: 290, protein: 7, carbs: 36, fat: 13, tags: ["pudim"] },
  { name: "Mousse de maracuja", quantity: "100g", calories: 220, protein: 3.3, carbs: 27, fat: 11, tags: ["mousse", "maracuja"] },
  { name: "Chocolate ao leite", quantity: "100g", calories: 535, protein: 7.6, carbs: 59.2, fat: 31.2, tags: ["chocolate"] },
  { name: "Chocolate meio amargo", quantity: "100g", calories: 546, protein: 7.2, carbs: 46.4, fat: 33.6, tags: ["chocolate"] },
  { name: "Sorvete de creme", quantity: "100g", calories: 207, protein: 3.5, carbs: 24, fat: 11, tags: ["sorvete", "creme"] },
  { name: "Doce de leite", quantity: "20g", calories: 63, protein: 1.1, carbs: 11.2, fat: 1.7, tags: ["doce de leite"] },
  { name: "Geleia de morango", quantity: "20g", calories: 52, protein: 0.1, carbs: 13, fat: 0, tags: ["geleia", "morango"] },
  { name: "Leite condensado", quantity: "20g", calories: 64, protein: 1.4, carbs: 11, fat: 1.6, tags: ["leite condensado"] },
  { name: "Acucar", quantity: "10g", calories: 39, protein: 0, carbs: 10, fat: 0, tags: ["acucar"] },
  { name: "Cafe com acucar", quantity: "200ml", calories: 40, protein: 0.2, carbs: 10, fat: 0, tags: ["cafe", "acucar"] },
  { name: "Cafe com leite", quantity: "200ml", calories: 82, protein: 4.1, carbs: 8.8, fat: 3.2, tags: ["cafe", "leite"] },
  { name: "Suco de laranja", quantity: "200ml", calories: 90, protein: 1.4, carbs: 20.7, fat: 0.2, tags: ["suco", "laranja"] },
  { name: "Suco de uva integral", quantity: "200ml", calories: 124, protein: 0.4, carbs: 31, fat: 0, tags: ["suco", "uva"] },
  { name: "Suco de maracuja", quantity: "200ml", calories: 84, protein: 0.5, carbs: 20, fat: 0.1, tags: ["suco", "maracuja"] },
  { name: "Refrigerante cola", quantity: "350ml", calories: 140, protein: 0, carbs: 35, fat: 0, tags: ["refrigerante", "cola"] },
  { name: "Guarana", quantity: "350ml", calories: 140, protein: 0, carbs: 35, fat: 0, tags: ["guarana", "refrigerante"] },
  { name: "Refrigerante laranja", quantity: "350ml", calories: 154, protein: 0, carbs: 39, fat: 0, tags: ["refrigerante", "laranja"] },
  { name: "Agua de coco", quantity: "200ml", calories: 38, protein: 0.7, carbs: 9.4, fat: 0.2, tags: ["agua", "coco"] },
  { name: "Azeite de oliva", quantity: "1 colher", calories: 119, protein: 0, carbs: 0, fat: 13.5, tags: ["azeite", "oliva"] },
  { name: "Margarina", quantity: "1 colher", calories: 100, protein: 0, carbs: 0, fat: 11.2, tags: ["margarina"] }
];
